query ($id: ID!) {
  products(where: { id: $id }) {
    id
    title
    category {
      title
    }
    brands {
      logo {
        url
      }
    }
    articul
    price
    description
    feature
    image {
      url
    }
    images {
      url
    }
  }
}
